# Generated by Django 5.0.7 on 2025-01-11 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=22, unique=True)),
                ('login', models.CharField(max_length=10, unique=True)),
                ('avatar', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Invalid avatar.', regex='^.{3}$')])),
                ('color', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Invalid color format.', regex='^[A-F0-9]{6}$')])),
            ],
        ),
    ]
