# Generated by Django 5.0.7 on 2025-01-05 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=22)),
                ('login', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Invalid color format.', regex='^[A-F0-9]{6}$')])),
            ],
        ),
    ]
